year: '2025'
site_name:
  en: Yago M Castro
  pt: Yago M Castro
author: Yago M Castro
language: en
repository: YagoMCastro/website
navigation:
  en:
    - name: Home
      id: index
    - name: Science
      id: science/index
    - name: Contact
      id: contact/index
contact:
  links:
  - icon: fas fa-envelope
    text: yagomcastro1@gmail.com
    url: mailto:yagomcastro1@gmail.com
  - icon: fab fa-linkedin
    text: LinkedIn
    url: https://linkedin.com/in/yago-moreira-castro-982b08184
  - icon: fab fa-github
    text: 'GitHub: @YagoMCastro'
    url: https://github.com/YagoMCastro
  title:
    en: Contact
    pt: Contato
ignore:
  - README.md
  - Makefile
